### ISSUE TITLE
Sugerencia cursoLaTex Cap. 1

### ISSUE THREAD

**Issue by efrainromano** [Ondiz/cursoLatex#7]
https://github.com/Ondiz/cursoLatex/blob/master/Contenido/01.Introduccion.tex
Me refiero a la L 84 

Además de Lyx, podrías mencionar otra excelente opción WYSIWYG, llamada GNU TeXmacs.

Sí deseas puedes hecharle un vistazo http://texmacs.org/tmweb/home/welcome.en.html

Yo lo uso, aunque siempre quise agarrar el Toro por los cuernos (migrar a LaTeX), no había encontrado nada breve y conciso, Con este curso ya agarre corage. 

Saludos

**Comment by Ondiz** [comment]
Añadida la mención a TeXmacs. ¡Gracias por la recomendación!
