### ISSUE TITLE
lfseries

### ISSUE THREAD

**Issue by johannesbottcher** [Ondiz/cursoLatex#9]
Hi, i just skimmed through your repo and came upon [`\lfseries`](https://github.com/Ondiz/cursoLatex/blob/master/Contenido/07.Formato.md#forma). I don't recall ever having heard of this. Where did you get that from?

**Comment by Ondiz** [comment]
Hi! I don't remember exactly I think it just came across in a random TeXExchange question (like [this one]), but it also appears in the [LaTeX wikibook]. 

[this one]: https://tex.stackexchange.com/questions/188726/textlf-for-light-font-weight-how-common
[LaTeX wikibook]: https://en.wikibooks.org/wiki/LaTeX/Fonts
